version: "3.8"
services:
  desktop:
    build:
      context: desktop
    environment:
      RESOLUTION: 1280x720
      USER: desktop
    ports:
      - 127.0.0.1:6081:80
      - 127.0.0.1:5901:5900
    volumes:
      - desktop_home:/home/desktop
      - ./desktop-xvfb.sh:/usr/local/bin/xvfb.sh
  discord:
    build:
      context: desktop
    environment:
      RESOLUTION: 1280x720
      USER: desktop
    ports:
      - 127.0.0.1:6080:80
      - 127.0.0.1:5900:5900
    volumes:
      - discord_home:/home/desktop
    ipc: host
    privileged: true
volumes:
  discord_home:
  desktop_home:
    driver: local
    driver_opts:
      o: "size=5000m"
      device: tmpfs
      type: tmpfs
